### ISSUE TITLE
Command to start?

### ISSUE THREAD

**Issue by CatarinaMartinsBE** [Menkalian/yumpu-dl-rs#1]
I compiled it, but then I can't get it working, can you explain what the procedure is?

**Comment by Menkalian** [comment]
Hi,

I just noticed I have not pushed everything I implemented when creating this.
I have added a simple runner and an example command.
Let me know whether it works for you.

As a warning: When testing I noticed some documents can not be downloaded using this progam. I am sorry if it does not work for you.
